version: "3.8"

services:
  mysqldb:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=  # No password
      - MYSQL_DATABASE=db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes  # Allow empty password
    ports:
      - "3306:3306"  # Correct MySQL port
    volumes:
      - db:/var/lib/mysql

  tpFoyer:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - "8086:8086"
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/db?useSSL=false",
          "spring.datasource.username": "root",
          "spring.datasource.password": "",  # No password
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    stdin_open: true
    tty: true

volumes:
  db:
